apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-app
  template:
    metadata:
      labels:
        app: log-app
    spec:
      containers:
      - name: log-app
        image: log-app:latest   # uses the imported local image
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: uploads
          mountPath: /uploads
      volumes:
      - name: uploads
        emptyDir: {}

